# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    user: postgres
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: user
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./database_backup:/docker-entrypoint-initdb.d
    # command: ["/bin/bash", "-c", "psql -U postgres -d postgres < postgres.sql"]
    ports:
      - "5432:5432"
volumes:
  pgdata: