# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    container_name: postgres
    working_dir: /var/lib/postgresql/data
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"