# Generated by Django 5.0.6 on 2024-05-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('base_currency', models.CharField(default='USD')),
                ('quote_currency', models.CharField()),
                ('exchange_rate', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
