# Generated by Django 5.0.6 on 2024-05-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='date',
            field=models.DateField(),
        ),
    ]
